- README.md
- docs/rules/globals.md
- lib/index.js
- lib/rules/globals.js
- lib/util/data/globalsExportedByPackages.js
- package.json
- tests/lib/rules/globals.js
This rule defines Meteor globals. It works in conjunction with ESLints no-undef.
closes #16
> feat(rule): Add rule: globals

- .eslintrc.yml
- docs/guides/setup.md
- package.json
- tests/.eslintrc.yml
- tests/lib/rules/audit-argument-checks.js
- tests/lib/rules/eventmap-params.js
use ESLint's own parsing capabilities instead
> refactor: remove babel-eslint dependency

- README.md
- docs/rules/prefix-eventmap-selectors.md
- lib/index.js
- lib/rules/prefix-eventmap-selectors.js
- package.json
- tests/lib/rules/prefix-eventmap-selectors.js
> feat(rule): add prefix-eventmap-selectors

- package.json
- add eslint-plugin-react
- update nyc
> add eslint plugin react

- README.md
- docs/rules/scope-dom-lookups.md
- lib/index.js
- lib/rules/scope-dom-lookups.js
- tests/lib/rules/scope-dom-lookups.js
> feat(rule): add rule scope-dom-lookups

- docs/rules/no-dom-lookup-on-created.md
- lib/index.js
- lib/rules/no-dom-lookup-on-created.js
- tests/lib/rules/no-dom-lookup-on-created.js
> feat(rule): add rule no-dom-lookup-on-created

- README.md
- docs/rules/no-template-parent-data.md
- lib/index.js
- lib/rules/no-template-parent-data.js
- tests/lib/rules/audit-argument-checks.js
- tests/lib/rules/no-template-parent-data.js
> feat(rule): add no-template-parent-data

- docs/guides/setup.md
removing trailing commas or adding missing commas where found in other examples
> fix(json configurations)

- README.md
> docs(README): fix broken links

- docs/rules/eventmap-params.md
- lib/rules/eventmap-params.js
- tests/lib/rules/eventmap-params.js
> feat(eventmap-params): add destructuring options

- package.json
It seems like v3 was unpublished 😕
> fix jsx a11y

- lib/rules/template-names.js
- tests/lib/rules/template-names.js
> feat(template-names): add upper-snake-case

- .travis.yml
> fix(ci): use npm@5.3.0

- package.json
> chore(package): update rewire to version 3.0.1

- package-lock.json
- package.json
I played with https://lgtm.com/projects/g/dferber90/eslint-plugin-meteor/ and find out about some unused dependencies.
- removes unused dependencies
- adds `package-lock.json`
> remove unused dependencies & add package-lock.json

- package-lock.json
- package.json
> make babel register a dev dep & upgrade semantic-release

- package-lock.json
- package.json
> chore: remove unused travis-deploy-once

- .codeclimate.yml
- .travis.yml
- README.md
- package-lock.json
This should make CI work again. We were not really using code-climate anyways.
> Remove code-climate & update lockfile

- package.json
> fix: pin eslint to 5.14.0

- .eslintrc.yml
- .travis.yml
- package-lock.json
- package.json
- scripts/new-rule.js
Drop eslint-config-airbnb, support eslint@6
closes #729
> chore: update dependencies

- .travis.yml
- lib/rules/audit-argument-checks.js
- lib/rules/eventmap-params.js
- lib/rules/no-dom-lookup-on-created.js
- lib/rules/no-session.js
- lib/rules/no-template-lifecycle-assignments.js
- lib/rules/no-template-parent-data.js
- lib/rules/no-zero-timeout.js
- lib/rules/prefer-session-equals.js
- lib/rules/prefix-eventmap-selectors.js
- lib/rules/scope-dom-lookups.js
- lib/rules/template-names.js
- lib/util/executors/sets.js
- lib/util/values.js
- package-lock.json
- package.json
- tests/index.js
closes #763
https://github.com/nodejs/Release/tree/5a579babfec65b0b8354693188ee7a28801a60e1
> Drop node 8

- lib/rules/audit-argument-checks.js
- tests/lib/rules/audit-argument-checks.js
> feat(audit-argument-checks): check default assignments

- docs/rules/audit-argument-checks.md
- lib/rules/audit-argument-checks.js
- tests/lib/rules/audit-argument-checks.js
Thanks to @edemaine who made #785!
I merged #785  to `next` before `master` so the CI can run.
> feat: allow assignment of check() return value (#785)
